### ISSUE TITLE
显示乐健不是最新版，有风险

### ISSUE THREAD

**Issue by 2913972274** [SuYueQiuLiang/SuYueQQBot#3]

**Comment by SuYueQiuLiang** [comment]
用管理员账号给机器人私信发送命令 "updateInsideVersion" ，命令需要管理员或以上权限，发送后会升级内置版本号，新的乐健版本没有修改跑步api，直接升级就行

**Comment by 2913972274** [comment]
> 用管理员账号给机器人私信发送命令 "updateInsideVersion" ，命令需要管理员或以上权限，发送后会升级内置版本号，新的乐健版本没有修改跑步api，直接升级就行

发送这个指令给他，他说没绑定账号，我用“setLezz”这个指令绑定账号了的
