### ISSUE TITLE
请问这个命令是怎么用的，能不能详细的讲一下，谢谢“Message addAdministrator userId &owner *NoAt /添加管理员权限”

### ISSUE THREAD

**Issue by 2913972274** [SuYueQiuLiang/SuYueQQBot#4]

**Comment by SuYueQiuLiang** [comment]
这个命令需要发起人拥有owner权限，在群聊中发送“addAdministrator qq号”或者"addAdministrator @某人"，也可以私聊中发送“addAdministrator qq号”，owner权限请手动写入配置文件中perms.cfg
示例：[{"perms":0,"userId":qq号}]
可以添加一个owner权限

**Comment by 2913972274** [comment]
> 这个命令需要发起人拥有owner权限，在群聊中发送“addAdministrator qq号”或者"addAdministrator @某人"，也可以私聊中发送“addAdministrator qq号”，owner权限请手动写入配置文件中perms.cfg
> 示例：[{"perms":0,"userId":qq号}]
> 可以添加一个owner权限

我配置好之后发送命令也没有反应
