### ISSUE TITLE
权限管理模块无法使用

### ISSUE THREAD

**Issue by freeloadsk** [SuYueQiuLiang/SuYueQQBot#6]
![image](https://user-images.githubusercontent.com/97888219/201504121-87086e86-fbcf-4625-a979-627b4c15c7d7.png)
由于所有权限都仅限bot拥有者才能使用，因此当拥有者列表为空时无法进行权限操作，均会在获取相关操作命令时返回空
![image](https://user-images.githubusercontent.com/97888219/201504155-b59fb31a-3e8e-4469-a349-e79d861fd6f7.png)

**Comment by SuYueQiuLiang** [comment]
当前版本请自行将权限列表手动写入根目录下perms.cfg文件，例：
[{"perms":0,"userId":qq号}]
如上可以预设一个owner权限的账号，保存文件重启框架后生效
